server.port: ${PORT:8086}

spring:
  application.name: arket-price-tracker
  profiles.active: ${PROFILE:prod}
  config.import: optional:file:.env[.properties] # enable scanning of .env file

price-checker.job:
  active: true
  refresh-interval-ms: 300000 # 5 minutes

sender:
  address: dario.mauri9@gmail.com
  password: ${SENDER_PASSWORD}
recipient.addresses: dario.mauri9@gmail.com # TODO configurable via GUI?

---
spring:
  config.activate.on-profile: dev
  h2.console.enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS MY_SCHEMA\;

vaadin.productionMode: false
---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.rsuhstqfoaoabfzgezxr
    password: ${DB_PASSWORD}

vaadin.productionMode: true
